// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.employee.app.grpc;

public interface EmployeeBaseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.employee.v1.EmployeeBase)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Name of the employee (e.g., Bruce Willis)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the employee (e.g., Bruce Willis)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Date of birth of the employee (e.g., 20-08-2021)
   * </pre>
   *
   * <code>string dob = 2;</code>
   * @return The dob.
   */
  java.lang.String getDob();
  /**
   * <pre>
   * Date of birth of the employee (e.g., 20-08-2021)
   * </pre>
   *
   * <code>string dob = 2;</code>
   * @return The bytes for dob.
   */
  com.google.protobuf.ByteString
      getDobBytes();

  /**
   * <pre>
   * Salary of the employee (e.g., 11214.50)
   * </pre>
   *
   * <code>string salary = 3;</code>
   * @return The salary.
   */
  java.lang.String getSalary();
  /**
   * <pre>
   * Salary of the employee (e.g., 11214.50)
   * </pre>
   *
   * <code>string salary = 3;</code>
   * @return The bytes for salary.
   */
  com.google.protobuf.ByteString
      getSalaryBytes();

  /**
   * <pre>
   * Age of the employee (e.g., 25)
   * </pre>
   *
   * <code>string age = 4;</code>
   * @return The age.
   */
  java.lang.String getAge();
  /**
   * <pre>
   * Age of the employee (e.g., 25)
   * </pre>
   *
   * <code>string age = 4;</code>
   * @return The bytes for age.
   */
  com.google.protobuf.ByteString
      getAgeBytes();
}
