// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.employee.app.grpc;

/**
 * Protobuf type {@code com.employee.v1.EmployeeBase}
 */
public final class EmployeeBase extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.employee.v1.EmployeeBase)
    EmployeeBaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeBase.newBuilder() to construct.
  private EmployeeBase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeBase() {
    name_ = "";
    dob_ = "";
    salary_ = "";
    age_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeBase();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeBase(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dob_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            salary_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            age_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeBase_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeBase_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.employee.app.grpc.EmployeeBase.class, com.employee.app.grpc.EmployeeBase.Builder.class);
  }

  public static final int NAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * Name of the employee (e.g., Bruce Willis)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Name of the employee (e.g., Bruce Willis)
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DOB_FIELD_NUMBER = 2;
  private volatile java.lang.Object dob_;
  /**
   * <pre>
   * Date of birth of the employee (e.g., 20-08-2021)
   * </pre>
   *
   * <code>string dob = 2;</code>
   * @return The dob.
   */
  @java.lang.Override
  public java.lang.String getDob() {
    java.lang.Object ref = dob_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dob_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Date of birth of the employee (e.g., 20-08-2021)
   * </pre>
   *
   * <code>string dob = 2;</code>
   * @return The bytes for dob.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDobBytes() {
    java.lang.Object ref = dob_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dob_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SALARY_FIELD_NUMBER = 3;
  private volatile java.lang.Object salary_;
  /**
   * <pre>
   * Salary of the employee (e.g., 11214.50)
   * </pre>
   *
   * <code>string salary = 3;</code>
   * @return The salary.
   */
  @java.lang.Override
  public java.lang.String getSalary() {
    java.lang.Object ref = salary_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      salary_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Salary of the employee (e.g., 11214.50)
   * </pre>
   *
   * <code>string salary = 3;</code>
   * @return The bytes for salary.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSalaryBytes() {
    java.lang.Object ref = salary_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      salary_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object age_;
  /**
   * <pre>
   * Age of the employee (e.g., 25)
   * </pre>
   *
   * <code>string age = 4;</code>
   * @return The age.
   */
  @java.lang.Override
  public java.lang.String getAge() {
    java.lang.Object ref = age_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      age_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Age of the employee (e.g., 25)
   * </pre>
   *
   * <code>string age = 4;</code>
   * @return The bytes for age.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAgeBytes() {
    java.lang.Object ref = age_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      age_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
    }
    if (!getDobBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dob_);
    }
    if (!getSalaryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, salary_);
    }
    if (!getAgeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, age_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
    }
    if (!getDobBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dob_);
    }
    if (!getSalaryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, salary_);
    }
    if (!getAgeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, age_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.employee.app.grpc.EmployeeBase)) {
      return super.equals(obj);
    }
    com.employee.app.grpc.EmployeeBase other = (com.employee.app.grpc.EmployeeBase) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getDob()
        .equals(other.getDob())) return false;
    if (!getSalary()
        .equals(other.getSalary())) return false;
    if (!getAge()
        .equals(other.getAge())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + DOB_FIELD_NUMBER;
    hash = (53 * hash) + getDob().hashCode();
    hash = (37 * hash) + SALARY_FIELD_NUMBER;
    hash = (53 * hash) + getSalary().hashCode();
    hash = (37 * hash) + AGE_FIELD_NUMBER;
    hash = (53 * hash) + getAge().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.employee.app.grpc.EmployeeBase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeBase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeBase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeBase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.employee.app.grpc.EmployeeBase prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.employee.v1.EmployeeBase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.employee.v1.EmployeeBase)
      com.employee.app.grpc.EmployeeBaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeBase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeBase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employee.app.grpc.EmployeeBase.class, com.employee.app.grpc.EmployeeBase.Builder.class);
    }

    // Construct using com.employee.app.grpc.EmployeeBase.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      name_ = "";

      dob_ = "";

      salary_ = "";

      age_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeBase_descriptor;
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeBase getDefaultInstanceForType() {
      return com.employee.app.grpc.EmployeeBase.getDefaultInstance();
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeBase build() {
      com.employee.app.grpc.EmployeeBase result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeBase buildPartial() {
      com.employee.app.grpc.EmployeeBase result = new com.employee.app.grpc.EmployeeBase(this);
      result.name_ = name_;
      result.dob_ = dob_;
      result.salary_ = salary_;
      result.age_ = age_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.employee.app.grpc.EmployeeBase) {
        return mergeFrom((com.employee.app.grpc.EmployeeBase)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.employee.app.grpc.EmployeeBase other) {
      if (other == com.employee.app.grpc.EmployeeBase.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getDob().isEmpty()) {
        dob_ = other.dob_;
        onChanged();
      }
      if (!other.getSalary().isEmpty()) {
        salary_ = other.salary_;
        onChanged();
      }
      if (!other.getAge().isEmpty()) {
        age_ = other.age_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.employee.app.grpc.EmployeeBase parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.employee.app.grpc.EmployeeBase) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * Name of the employee (e.g., Bruce Willis)
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Name of the employee (e.g., Bruce Willis)
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Name of the employee (e.g., Bruce Willis)
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the employee (e.g., Bruce Willis)
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Name of the employee (e.g., Bruce Willis)
     * </pre>
     *
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dob_ = "";
    /**
     * <pre>
     * Date of birth of the employee (e.g., 20-08-2021)
     * </pre>
     *
     * <code>string dob = 2;</code>
     * @return The dob.
     */
    public java.lang.String getDob() {
      java.lang.Object ref = dob_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dob_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Date of birth of the employee (e.g., 20-08-2021)
     * </pre>
     *
     * <code>string dob = 2;</code>
     * @return The bytes for dob.
     */
    public com.google.protobuf.ByteString
        getDobBytes() {
      java.lang.Object ref = dob_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Date of birth of the employee (e.g., 20-08-2021)
     * </pre>
     *
     * <code>string dob = 2;</code>
     * @param value The dob to set.
     * @return This builder for chaining.
     */
    public Builder setDob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dob_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date of birth of the employee (e.g., 20-08-2021)
     * </pre>
     *
     * <code>string dob = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearDob() {
      
      dob_ = getDefaultInstance().getDob();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Date of birth of the employee (e.g., 20-08-2021)
     * </pre>
     *
     * <code>string dob = 2;</code>
     * @param value The bytes for dob to set.
     * @return This builder for chaining.
     */
    public Builder setDobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dob_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object salary_ = "";
    /**
     * <pre>
     * Salary of the employee (e.g., 11214.50)
     * </pre>
     *
     * <code>string salary = 3;</code>
     * @return The salary.
     */
    public java.lang.String getSalary() {
      java.lang.Object ref = salary_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        salary_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Salary of the employee (e.g., 11214.50)
     * </pre>
     *
     * <code>string salary = 3;</code>
     * @return The bytes for salary.
     */
    public com.google.protobuf.ByteString
        getSalaryBytes() {
      java.lang.Object ref = salary_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        salary_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Salary of the employee (e.g., 11214.50)
     * </pre>
     *
     * <code>string salary = 3;</code>
     * @param value The salary to set.
     * @return This builder for chaining.
     */
    public Builder setSalary(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      salary_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Salary of the employee (e.g., 11214.50)
     * </pre>
     *
     * <code>string salary = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSalary() {
      
      salary_ = getDefaultInstance().getSalary();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Salary of the employee (e.g., 11214.50)
     * </pre>
     *
     * <code>string salary = 3;</code>
     * @param value The bytes for salary to set.
     * @return This builder for chaining.
     */
    public Builder setSalaryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      salary_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object age_ = "";
    /**
     * <pre>
     * Age of the employee (e.g., 25)
     * </pre>
     *
     * <code>string age = 4;</code>
     * @return The age.
     */
    public java.lang.String getAge() {
      java.lang.Object ref = age_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        age_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Age of the employee (e.g., 25)
     * </pre>
     *
     * <code>string age = 4;</code>
     * @return The bytes for age.
     */
    public com.google.protobuf.ByteString
        getAgeBytes() {
      java.lang.Object ref = age_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        age_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Age of the employee (e.g., 25)
     * </pre>
     *
     * <code>string age = 4;</code>
     * @param value The age to set.
     * @return This builder for chaining.
     */
    public Builder setAge(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      age_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Age of the employee (e.g., 25)
     * </pre>
     *
     * <code>string age = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearAge() {
      
      age_ = getDefaultInstance().getAge();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Age of the employee (e.g., 25)
     * </pre>
     *
     * <code>string age = 4;</code>
     * @param value The bytes for age to set.
     * @return This builder for chaining.
     */
    public Builder setAgeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      age_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.employee.v1.EmployeeBase)
  }

  // @@protoc_insertion_point(class_scope:com.employee.v1.EmployeeBase)
  private static final com.employee.app.grpc.EmployeeBase DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.employee.app.grpc.EmployeeBase();
  }

  public static com.employee.app.grpc.EmployeeBase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeBase>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeBase>() {
    @java.lang.Override
    public EmployeeBase parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeBase(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeBase> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeBase> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.employee.app.grpc.EmployeeBase getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

