/*
 * Copyright 2002-2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.employee.app.grpc;

/**
 * Protobuf type {@code com.employee.v1.EmployeeRequest}
 */
public final class EmployeeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.employee.v1.EmployeeRequest)
    EmployeeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EmployeeRequest.newBuilder() to construct.
  private EmployeeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EmployeeRequest() {
    employee_ = java.util.Collections.emptyList();
    fileType_ = 0;
    name_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EmployeeRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EmployeeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              employee_ = new java.util.ArrayList<com.employee.app.grpc.EmployeeBase>();
              mutable_bitField0_ |= 0x00000001;
            }
            employee_.add(
                input.readMessage(com.employee.app.grpc.EmployeeBase.parser(), extensionRegistry));
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            fileType_ = rawValue;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        employee_ = java.util.Collections.unmodifiableList(employee_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.employee.app.grpc.EmployeeRequest.class, com.employee.app.grpc.EmployeeRequest.Builder.class);
  }

  /**
   * <pre>
   * available file formats
   * </pre>
   *
   * Protobuf enum {@code com.employee.v1.EmployeeRequest.FileFormat}
   */
  public enum FileFormat
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CSV = 0;</code>
     */
    CSV(0),
    /**
     * <code>XML = 1;</code>
     */
    XML(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>CSV = 0;</code>
     */
    public static final int CSV_VALUE = 0;
    /**
     * <code>XML = 1;</code>
     */
    public static final int XML_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FileFormat valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static FileFormat forNumber(int value) {
      switch (value) {
        case 0: return CSV;
        case 1: return XML;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FileFormat>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FileFormat> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FileFormat>() {
            public FileFormat findValueByNumber(int number) {
              return FileFormat.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.employee.app.grpc.EmployeeRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final FileFormat[] VALUES = values();

    public static FileFormat valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FileFormat(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.employee.v1.EmployeeRequest.FileFormat)
  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.employee.v1.EmployeeRequest.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * Records Number is the quantity of employee records in the file.
     * </pre>
     *
     * <code>string recordsNum = 2;</code>
     * @return The recordsNum.
     */
    java.lang.String getRecordsNum();
    /**
     * <pre>
     * Records Number is the quantity of employee records in the file.
     * </pre>
     *
     * <code>string recordsNum = 2;</code>
     * @return The bytes for recordsNum.
     */
    com.google.protobuf.ByteString
        getRecordsNumBytes();

    /**
     * <pre>
     * File uri.
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The uri.
     */
    java.lang.String getUri();
    /**
     * <pre>
     * File uri.
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The bytes for uri.
     */
    com.google.protobuf.ByteString
        getUriBytes();

    /**
     * <pre>
     * File type.
     * </pre>
     *
     * <code>string type = 4;</code>
     * @return The type.
     */
    java.lang.String getType();
    /**
     * <pre>
     * File type.
     * </pre>
     *
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <pre>
     * File size.
     * </pre>
     *
     * <code>string size = 5;</code>
     * @return The size.
     */
    java.lang.String getSize();
    /**
     * <pre>
     * File size.
     * </pre>
     *
     * <code>string size = 5;</code>
     * @return The bytes for size.
     */
    com.google.protobuf.ByteString
        getSizeBytes();
  }
  /**
   * Protobuf type {@code com.employee.v1.EmployeeRequest.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.employee.v1.EmployeeRequest.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      name_ = "";
      recordsNum_ = "";
      uri_ = "";
      type_ = "";
      size_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              recordsNum_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              uri_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              size_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employee.app.grpc.EmployeeRequest.Response.class, com.employee.app.grpc.EmployeeRequest.Response.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RECORDSNUM_FIELD_NUMBER = 2;
    private volatile java.lang.Object recordsNum_;
    /**
     * <pre>
     * Records Number is the quantity of employee records in the file.
     * </pre>
     *
     * <code>string recordsNum = 2;</code>
     * @return The recordsNum.
     */
    @java.lang.Override
    public java.lang.String getRecordsNum() {
      java.lang.Object ref = recordsNum_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        recordsNum_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Records Number is the quantity of employee records in the file.
     * </pre>
     *
     * <code>string recordsNum = 2;</code>
     * @return The bytes for recordsNum.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRecordsNumBytes() {
      java.lang.Object ref = recordsNum_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        recordsNum_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URI_FIELD_NUMBER = 3;
    private volatile java.lang.Object uri_;
    /**
     * <pre>
     * File uri.
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The uri.
     */
    @java.lang.Override
    public java.lang.String getUri() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uri_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * File uri.
     * </pre>
     *
     * <code>string uri = 3;</code>
     * @return The bytes for uri.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUriBytes() {
      java.lang.Object ref = uri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object type_;
    /**
     * <pre>
     * File type.
     * </pre>
     *
     * <code>string type = 4;</code>
     * @return The type.
     */
    @java.lang.Override
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * File type.
     * </pre>
     *
     * <code>string type = 4;</code>
     * @return The bytes for type.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SIZE_FIELD_NUMBER = 5;
    private volatile java.lang.Object size_;
    /**
     * <pre>
     * File size.
     * </pre>
     *
     * <code>string size = 5;</code>
     * @return The size.
     */
    @java.lang.Override
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * File size.
     * </pre>
     *
     * <code>string size = 5;</code>
     * @return The bytes for size.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getRecordsNumBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, recordsNum_);
      }
      if (!getUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, uri_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, type_);
      }
      if (!getSizeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, size_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getRecordsNumBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, recordsNum_);
      }
      if (!getUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, uri_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, type_);
      }
      if (!getSizeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, size_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.employee.app.grpc.EmployeeRequest.Response)) {
        return super.equals(obj);
      }
      com.employee.app.grpc.EmployeeRequest.Response other = (com.employee.app.grpc.EmployeeRequest.Response) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getRecordsNum()
          .equals(other.getRecordsNum())) return false;
      if (!getUri()
          .equals(other.getUri())) return false;
      if (!getType()
          .equals(other.getType())) return false;
      if (!getSize()
          .equals(other.getSize())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + RECORDSNUM_FIELD_NUMBER;
      hash = (53 * hash) + getRecordsNum().hashCode();
      hash = (37 * hash) + URI_FIELD_NUMBER;
      hash = (53 * hash) + getUri().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.employee.app.grpc.EmployeeRequest.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.employee.app.grpc.EmployeeRequest.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.employee.v1.EmployeeRequest.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.employee.v1.EmployeeRequest.Response)
        com.employee.app.grpc.EmployeeRequest.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.employee.app.grpc.EmployeeRequest.Response.class, com.employee.app.grpc.EmployeeRequest.Response.Builder.class);
      }

      // Construct using com.employee.app.grpc.EmployeeRequest.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        recordsNum_ = "";

        uri_ = "";

        type_ = "";

        size_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_Response_descriptor;
      }

      @java.lang.Override
      public com.employee.app.grpc.EmployeeRequest.Response getDefaultInstanceForType() {
        return com.employee.app.grpc.EmployeeRequest.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.employee.app.grpc.EmployeeRequest.Response build() {
        com.employee.app.grpc.EmployeeRequest.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.employee.app.grpc.EmployeeRequest.Response buildPartial() {
        com.employee.app.grpc.EmployeeRequest.Response result = new com.employee.app.grpc.EmployeeRequest.Response(this);
        result.name_ = name_;
        result.recordsNum_ = recordsNum_;
        result.uri_ = uri_;
        result.type_ = type_;
        result.size_ = size_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.employee.app.grpc.EmployeeRequest.Response) {
          return mergeFrom((com.employee.app.grpc.EmployeeRequest.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.employee.app.grpc.EmployeeRequest.Response other) {
        if (other == com.employee.app.grpc.EmployeeRequest.Response.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getRecordsNum().isEmpty()) {
          recordsNum_ = other.recordsNum_;
          onChanged();
        }
        if (!other.getUri().isEmpty()) {
          uri_ = other.uri_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getSize().isEmpty()) {
          size_ = other.size_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.employee.app.grpc.EmployeeRequest.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.employee.app.grpc.EmployeeRequest.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * File Name is the common name of the file.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * File Name is the common name of the file.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * File Name is the common name of the file.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File Name is the common name of the file.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File Name is the common name of the file.
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object recordsNum_ = "";
      /**
       * <pre>
       * Records Number is the quantity of employee records in the file.
       * </pre>
       *
       * <code>string recordsNum = 2;</code>
       * @return The recordsNum.
       */
      public java.lang.String getRecordsNum() {
        java.lang.Object ref = recordsNum_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          recordsNum_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Records Number is the quantity of employee records in the file.
       * </pre>
       *
       * <code>string recordsNum = 2;</code>
       * @return The bytes for recordsNum.
       */
      public com.google.protobuf.ByteString
          getRecordsNumBytes() {
        java.lang.Object ref = recordsNum_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          recordsNum_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Records Number is the quantity of employee records in the file.
       * </pre>
       *
       * <code>string recordsNum = 2;</code>
       * @param value The recordsNum to set.
       * @return This builder for chaining.
       */
      public Builder setRecordsNum(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        recordsNum_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Records Number is the quantity of employee records in the file.
       * </pre>
       *
       * <code>string recordsNum = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRecordsNum() {
        
        recordsNum_ = getDefaultInstance().getRecordsNum();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Records Number is the quantity of employee records in the file.
       * </pre>
       *
       * <code>string recordsNum = 2;</code>
       * @param value The bytes for recordsNum to set.
       * @return This builder for chaining.
       */
      public Builder setRecordsNumBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        recordsNum_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object uri_ = "";
      /**
       * <pre>
       * File uri.
       * </pre>
       *
       * <code>string uri = 3;</code>
       * @return The uri.
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * File uri.
       * </pre>
       *
       * <code>string uri = 3;</code>
       * @return The bytes for uri.
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * File uri.
       * </pre>
       *
       * <code>string uri = 3;</code>
       * @param value The uri to set.
       * @return This builder for chaining.
       */
      public Builder setUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uri_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File uri.
       * </pre>
       *
       * <code>string uri = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUri() {
        
        uri_ = getDefaultInstance().getUri();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File uri.
       * </pre>
       *
       * <code>string uri = 3;</code>
       * @param value The bytes for uri to set.
       * @return This builder for chaining.
       */
      public Builder setUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        uri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object type_ = "";
      /**
       * <pre>
       * File type.
       * </pre>
       *
       * <code>string type = 4;</code>
       * @return The type.
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * File type.
       * </pre>
       *
       * <code>string type = 4;</code>
       * @return The bytes for type.
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * File type.
       * </pre>
       *
       * <code>string type = 4;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File type.
       * </pre>
       *
       * <code>string type = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File type.
       * </pre>
       *
       * <code>string type = 4;</code>
       * @param value The bytes for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object size_ = "";
      /**
       * <pre>
       * File size.
       * </pre>
       *
       * <code>string size = 5;</code>
       * @return The size.
       */
      public java.lang.String getSize() {
        java.lang.Object ref = size_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          size_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * File size.
       * </pre>
       *
       * <code>string size = 5;</code>
       * @return The bytes for size.
       */
      public com.google.protobuf.ByteString
          getSizeBytes() {
        java.lang.Object ref = size_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          size_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * File size.
       * </pre>
       *
       * <code>string size = 5;</code>
       * @param value The size to set.
       * @return This builder for chaining.
       */
      public Builder setSize(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File size.
       * </pre>
       *
       * <code>string size = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSize() {
        
        size_ = getDefaultInstance().getSize();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * File size.
       * </pre>
       *
       * <code>string size = 5;</code>
       * @param value The bytes for size to set.
       * @return This builder for chaining.
       */
      public Builder setSizeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        size_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.employee.v1.EmployeeRequest.Response)
    }

    // @@protoc_insertion_point(class_scope:com.employee.v1.EmployeeRequest.Response)
    private static final com.employee.app.grpc.EmployeeRequest.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.employee.app.grpc.EmployeeRequest.Response();
    }

    public static com.employee.app.grpc.EmployeeRequest.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeRequest.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public static final int EMPLOYEE_FIELD_NUMBER = 1;
  private java.util.List<com.employee.app.grpc.EmployeeBase> employee_;
  /**
   * <pre>
   * List of employees
   * </pre>
   *
   * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
   */
  @java.lang.Override
  public java.util.List<com.employee.app.grpc.EmployeeBase> getEmployeeList() {
    return employee_;
  }
  /**
   * <pre>
   * List of employees
   * </pre>
   *
   * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.employee.app.grpc.EmployeeBaseOrBuilder> 
      getEmployeeOrBuilderList() {
    return employee_;
  }
  /**
   * <pre>
   * List of employees
   * </pre>
   *
   * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
   */
  @java.lang.Override
  public int getEmployeeCount() {
    return employee_.size();
  }
  /**
   * <pre>
   * List of employees
   * </pre>
   *
   * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
   */
  @java.lang.Override
  public com.employee.app.grpc.EmployeeBase getEmployee(int index) {
    return employee_.get(index);
  }
  /**
   * <pre>
   * List of employees
   * </pre>
   *
   * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
   */
  @java.lang.Override
  public com.employee.app.grpc.EmployeeBaseOrBuilder getEmployeeOrBuilder(
      int index) {
    return employee_.get(index);
  }

  public static final int FILETYPE_FIELD_NUMBER = 2;
  private int fileType_;
  /**
   * <pre>
   * File format
   * </pre>
   *
   * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
   * @return The enum numeric value on the wire for fileType.
   */
  @java.lang.Override public int getFileTypeValue() {
    return fileType_;
  }
  /**
   * <pre>
   * File format
   * </pre>
   *
   * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
   * @return The fileType.
   */
  @java.lang.Override public com.employee.app.grpc.EmployeeRequest.FileFormat getFileType() {
    @SuppressWarnings("deprecation")
    com.employee.app.grpc.EmployeeRequest.FileFormat result = com.employee.app.grpc.EmployeeRequest.FileFormat.valueOf(fileType_);
    return result == null ? com.employee.app.grpc.EmployeeRequest.FileFormat.UNRECOGNIZED : result;
  }

  public static final int NAME_FIELD_NUMBER = 3;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * File Name is the common name of the file.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * File Name is the common name of the file.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < employee_.size(); i++) {
      output.writeMessage(1, employee_.get(i));
    }
    if (fileType_ != com.employee.app.grpc.EmployeeRequest.FileFormat.CSV.getNumber()) {
      output.writeEnum(2, fileType_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < employee_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, employee_.get(i));
    }
    if (fileType_ != com.employee.app.grpc.EmployeeRequest.FileFormat.CSV.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, fileType_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.employee.app.grpc.EmployeeRequest)) {
      return super.equals(obj);
    }
    com.employee.app.grpc.EmployeeRequest other = (com.employee.app.grpc.EmployeeRequest) obj;

    if (!getEmployeeList()
        .equals(other.getEmployeeList())) return false;
    if (fileType_ != other.fileType_) return false;
    if (!getName()
        .equals(other.getName())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getEmployeeCount() > 0) {
      hash = (37 * hash) + EMPLOYEE_FIELD_NUMBER;
      hash = (53 * hash) + getEmployeeList().hashCode();
    }
    hash = (37 * hash) + FILETYPE_FIELD_NUMBER;
    hash = (53 * hash) + fileType_;
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.employee.app.grpc.EmployeeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.employee.app.grpc.EmployeeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.employee.v1.EmployeeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.employee.v1.EmployeeRequest)
      com.employee.app.grpc.EmployeeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.employee.app.grpc.EmployeeRequest.class, com.employee.app.grpc.EmployeeRequest.Builder.class);
    }

    // Construct using com.employee.app.grpc.EmployeeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmployeeFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (employeeBuilder_ == null) {
        employee_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        employeeBuilder_.clear();
      }
      fileType_ = 0;

      name_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.employee.app.grpc.EmployeeServiceOuterClass.internal_static_com_employee_v1_EmployeeRequest_descriptor;
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeRequest getDefaultInstanceForType() {
      return com.employee.app.grpc.EmployeeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeRequest build() {
      com.employee.app.grpc.EmployeeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.employee.app.grpc.EmployeeRequest buildPartial() {
      com.employee.app.grpc.EmployeeRequest result = new com.employee.app.grpc.EmployeeRequest(this);
      int from_bitField0_ = bitField0_;
      if (employeeBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          employee_ = java.util.Collections.unmodifiableList(employee_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.employee_ = employee_;
      } else {
        result.employee_ = employeeBuilder_.build();
      }
      result.fileType_ = fileType_;
      result.name_ = name_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.employee.app.grpc.EmployeeRequest) {
        return mergeFrom((com.employee.app.grpc.EmployeeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.employee.app.grpc.EmployeeRequest other) {
      if (other == com.employee.app.grpc.EmployeeRequest.getDefaultInstance()) return this;
      if (employeeBuilder_ == null) {
        if (!other.employee_.isEmpty()) {
          if (employee_.isEmpty()) {
            employee_ = other.employee_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmployeeIsMutable();
            employee_.addAll(other.employee_);
          }
          onChanged();
        }
      } else {
        if (!other.employee_.isEmpty()) {
          if (employeeBuilder_.isEmpty()) {
            employeeBuilder_.dispose();
            employeeBuilder_ = null;
            employee_ = other.employee_;
            bitField0_ = (bitField0_ & ~0x00000001);
            employeeBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getEmployeeFieldBuilder() : null;
          } else {
            employeeBuilder_.addAllMessages(other.employee_);
          }
        }
      }
      if (other.fileType_ != 0) {
        setFileTypeValue(other.getFileTypeValue());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.employee.app.grpc.EmployeeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.employee.app.grpc.EmployeeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.employee.app.grpc.EmployeeBase> employee_ =
      java.util.Collections.emptyList();
    private void ensureEmployeeIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        employee_ = new java.util.ArrayList<com.employee.app.grpc.EmployeeBase>(employee_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.employee.app.grpc.EmployeeBase, com.employee.app.grpc.EmployeeBase.Builder, com.employee.app.grpc.EmployeeBaseOrBuilder> employeeBuilder_;

    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public java.util.List<com.employee.app.grpc.EmployeeBase> getEmployeeList() {
      if (employeeBuilder_ == null) {
        return java.util.Collections.unmodifiableList(employee_);
      } else {
        return employeeBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public int getEmployeeCount() {
      if (employeeBuilder_ == null) {
        return employee_.size();
      } else {
        return employeeBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public com.employee.app.grpc.EmployeeBase getEmployee(int index) {
      if (employeeBuilder_ == null) {
        return employee_.get(index);
      } else {
        return employeeBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder setEmployee(
        int index, com.employee.app.grpc.EmployeeBase value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.set(index, value);
        onChanged();
      } else {
        employeeBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder setEmployee(
        int index, com.employee.app.grpc.EmployeeBase.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.set(index, builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder addEmployee(com.employee.app.grpc.EmployeeBase value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.add(value);
        onChanged();
      } else {
        employeeBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder addEmployee(
        int index, com.employee.app.grpc.EmployeeBase value) {
      if (employeeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmployeeIsMutable();
        employee_.add(index, value);
        onChanged();
      } else {
        employeeBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder addEmployee(
        com.employee.app.grpc.EmployeeBase.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.add(builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder addEmployee(
        int index, com.employee.app.grpc.EmployeeBase.Builder builderForValue) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.add(index, builderForValue.build());
        onChanged();
      } else {
        employeeBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder addAllEmployee(
        java.lang.Iterable<? extends com.employee.app.grpc.EmployeeBase> values) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, employee_);
        onChanged();
      } else {
        employeeBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder clearEmployee() {
      if (employeeBuilder_ == null) {
        employee_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        employeeBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public Builder removeEmployee(int index) {
      if (employeeBuilder_ == null) {
        ensureEmployeeIsMutable();
        employee_.remove(index);
        onChanged();
      } else {
        employeeBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public com.employee.app.grpc.EmployeeBase.Builder getEmployeeBuilder(
        int index) {
      return getEmployeeFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public com.employee.app.grpc.EmployeeBaseOrBuilder getEmployeeOrBuilder(
        int index) {
      if (employeeBuilder_ == null) {
        return employee_.get(index);  } else {
        return employeeBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public java.util.List<? extends com.employee.app.grpc.EmployeeBaseOrBuilder> 
         getEmployeeOrBuilderList() {
      if (employeeBuilder_ != null) {
        return employeeBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(employee_);
      }
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public com.employee.app.grpc.EmployeeBase.Builder addEmployeeBuilder() {
      return getEmployeeFieldBuilder().addBuilder(
          com.employee.app.grpc.EmployeeBase.getDefaultInstance());
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public com.employee.app.grpc.EmployeeBase.Builder addEmployeeBuilder(
        int index) {
      return getEmployeeFieldBuilder().addBuilder(
          index, com.employee.app.grpc.EmployeeBase.getDefaultInstance());
    }
    /**
     * <pre>
     * List of employees
     * </pre>
     *
     * <code>repeated .com.employee.v1.EmployeeBase employee = 1;</code>
     */
    public java.util.List<com.employee.app.grpc.EmployeeBase.Builder> 
         getEmployeeBuilderList() {
      return getEmployeeFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.employee.app.grpc.EmployeeBase, com.employee.app.grpc.EmployeeBase.Builder, com.employee.app.grpc.EmployeeBaseOrBuilder> 
        getEmployeeFieldBuilder() {
      if (employeeBuilder_ == null) {
        employeeBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.employee.app.grpc.EmployeeBase, com.employee.app.grpc.EmployeeBase.Builder, com.employee.app.grpc.EmployeeBaseOrBuilder>(
                employee_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        employee_ = null;
      }
      return employeeBuilder_;
    }

    private int fileType_ = 0;
    /**
     * <pre>
     * File format
     * </pre>
     *
     * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
     * @return The enum numeric value on the wire for fileType.
     */
    @java.lang.Override public int getFileTypeValue() {
      return fileType_;
    }
    /**
     * <pre>
     * File format
     * </pre>
     *
     * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
     * @param value The enum numeric value on the wire for fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileTypeValue(int value) {
      
      fileType_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File format
     * </pre>
     *
     * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
     * @return The fileType.
     */
    @java.lang.Override
    public com.employee.app.grpc.EmployeeRequest.FileFormat getFileType() {
      @SuppressWarnings("deprecation")
      com.employee.app.grpc.EmployeeRequest.FileFormat result = com.employee.app.grpc.EmployeeRequest.FileFormat.valueOf(fileType_);
      return result == null ? com.employee.app.grpc.EmployeeRequest.FileFormat.UNRECOGNIZED : result;
    }
    /**
     * <pre>
     * File format
     * </pre>
     *
     * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
     * @param value The fileType to set.
     * @return This builder for chaining.
     */
    public Builder setFileType(com.employee.app.grpc.EmployeeRequest.FileFormat value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      fileType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File format
     * </pre>
     *
     * <code>.com.employee.v1.EmployeeRequest.FileFormat fileType = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearFileType() {
      
      fileType_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * File Name is the common name of the file.
     * </pre>
     *
     * <code>string name = 3;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.employee.v1.EmployeeRequest)
  }

  // @@protoc_insertion_point(class_scope:com.employee.v1.EmployeeRequest)
  private static final com.employee.app.grpc.EmployeeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.employee.app.grpc.EmployeeRequest();
  }

  public static com.employee.app.grpc.EmployeeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EmployeeRequest>
      PARSER = new com.google.protobuf.AbstractParser<EmployeeRequest>() {
    @java.lang.Override
    public EmployeeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EmployeeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EmployeeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EmployeeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.employee.app.grpc.EmployeeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

