/*
 * Copyright 2002-2021 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmployeeService.proto

package com.employee.app.grpc;

public final class EmployeeServiceOuterClass {
  private EmployeeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_employee_v1_EmployeeBase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_employee_v1_EmployeeBase_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_employee_v1_EmployeeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_employee_v1_EmployeeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_employee_v1_EmployeeRequest_Response_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_employee_v1_EmployeeRequest_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025EmployeeService.proto\022\017com.employee.v1" +
      "\"F\n\014EmployeeBase\022\014\n\004name\030\001 \001(\t\022\013\n\003dob\030\002 " +
      "\001(\t\022\016\n\006salary\030\003 \001(\t\022\013\n\003age\030\004 \001(\t\"\206\002\n\017Emp" +
      "loyeeRequest\022/\n\010employee\030\001 \003(\0132\035.com.emp" +
      "loyee.v1.EmployeeBase\022=\n\010fileType\030\002 \001(\0162" +
      "+.com.employee.v1.EmployeeRequest.FileFo" +
      "rmat\022\014\n\004name\030\003 \001(\t\032U\n\010Response\022\014\n\004name\030\001" +
      " \001(\t\022\022\n\nrecordsNum\030\002 \001(\t\022\013\n\003uri\030\003 \001(\t\022\014\n" +
      "\004type\030\004 \001(\t\022\014\n\004size\030\005 \001(\t\"\036\n\nFileFormat\022" +
      "\007\n\003CSV\020\000\022\007\n\003XML\020\0012\277\001\n\017EmployeeService\022U\n" +
      "\006Create\022 .com.employee.v1.EmployeeReques" +
      "t\032).com.employee.v1.EmployeeRequest.Resp" +
      "onse\022U\n\006Update\022 .com.employee.v1.Employe" +
      "eRequest\032).com.employee.v1.EmployeeReque" +
      "st.ResponseB\031\n\025com.employee.app.grpcP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_employee_v1_EmployeeBase_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_employee_v1_EmployeeBase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_employee_v1_EmployeeBase_descriptor,
        new java.lang.String[] { "Name", "Dob", "Salary", "Age", });
    internal_static_com_employee_v1_EmployeeRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_employee_v1_EmployeeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_employee_v1_EmployeeRequest_descriptor,
        new java.lang.String[] { "Employee", "FileType", "Name", });
    internal_static_com_employee_v1_EmployeeRequest_Response_descriptor =
      internal_static_com_employee_v1_EmployeeRequest_descriptor.getNestedTypes().get(0);
    internal_static_com_employee_v1_EmployeeRequest_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_employee_v1_EmployeeRequest_Response_descriptor,
        new java.lang.String[] { "Name", "RecordsNum", "Uri", "Type", "Size", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
